version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  nats-streaming:
    image: nats-streaming:latest
    container_name: nats_streaming
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"

  go-web-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDRESS: "localhost:8080"
      DB_ADDRESS: "postgres://test:test@postgres:5432/test"
      NATS_ADDRESS: "nats-streaming:4222"